import { Fact } from '@/types/fact';

export const facts: Fact[] = [
    {
        id: '1',
        text: 'Hummingbirds are the only birds capable of sustained backward flight due to a unique ball-and-socket shoulder joint that allows their wings to rotate in a full 180-degree arc.',
        imageKeyword: 'hummingbird',
        category: 'animals',
    },
    {
        id: '2',
        text: 'A hummingbird\'s heart can beat over 1,200 times per minute during flight, making it one of the fastest heart rates among vertebrates.',
        imageKeyword: 'hummingbird wings',
        category: 'animals',
    },
    {
        id: '3',
        text: 'Long-tailed tits build elastic nests using spider silk, which allows the nest to expand as the chicks grow without breaking.',
        imageKeyword: 'long-tailed tit nest',
        category: 'animals',
    },
    {
        id: '4',
        text: 'Long-tailed tits practice cooperative breeding, meaning related adults often help raise each other\'s offspring if their own nests fail.',
        imageKeyword: 'long-tailed tit',
        category: 'animals',
    },
    {
        id: '5',
        text: 'Cats have a specialized collarbone that does not attach to other bones, allowing them to squeeze through openings roughly the size of their head.',
        imageKeyword: 'cat squeezing through gap',
        category: 'animals',
    },
    {
        id: '6',
        text: 'Dogs can understand up to 200 human words on average, and some highly trained individuals have demonstrated vocabularies exceeding 1,000 words.',
        imageKeyword: 'dog listening',
        category: 'animals',
    },
    {
        id: '7',
        text: 'When a cat slowly blinks at a human, it is often interpreted as a sign of trust and affiliative behavior in feline social communication.',
        imageKeyword: 'cat slow blink',
        category: 'animals',
    },
    {
        id: '8',
        text: 'The Edelweiss flower survives extreme alpine conditions by being covered in tiny white hairs that protect it from ultraviolet radiation and cold temperatures.',
        imageKeyword: 'edelweiss flower',
        category: 'flowers',
    },
    {
        id: '9',
        text: 'Sunflowers can exhibit heliotropism during their growth phase, tracking the Sun across the sky to maximize photosynthesis efficiency.',
        imageKeyword: 'sunflower field',
        category: 'flowers',
    },
    {
        id: '10',
        text: 'Forget-me-nots became a symbol of remembrance in Europe because of a medieval legend in which a knight threw the flowers to his beloved before drowning.',
        imageKeyword: 'forget-me-not flower',
        category: 'flowers',
    },
    {
        id: '11',
        text: 'Nikola Tesla conceptualized wireless energy transmission in the late 19th century and built the Wardenclyffe Tower to attempt large-scale wireless communication.',
        imageKeyword: 'tesla tower',
        category: 'physics history',
    },
    {
        id: '12',
        text: 'Nikola Tesla reportedly memorized entire books and performed complex integral calculus in his head, relying heavily on visual imagination rather than written notes.',
        imageKeyword: 'tesla coil',
        category: 'physics history',
    },
    {
        id: '13',
        text: 'Marie Curie was the first person to win Nobel Prizes in two different scientific fields: Physics and Chemistry.',
        imageKeyword: 'radioactive research',
        category: 'important women',
    },
    {
        id: '14',
        text: 'Marie Curie refused to patent the radium isolation process, believing that scientific discoveries should remain accessible for the benefit of humanity.',
        imageKeyword: 'radiation lab',
        category: 'important women',
    },
    {
        id: '15',
        text: 'Dr. Jolanta Wadowska-Król organized medical screening campaigns in Poland that identified and treated thousands of children affected by industrial lead poisoning.',
        imageKeyword: 'medical screening clinic',
        category: 'important women',
    },
    {
        id: '16',
        text: 'During World War II, Yugoslav Partisan units established underground schools and cultural institutions, preserving education and literature despite occupation.',
        imageKeyword: 'yugoslav partisans',
        category: 'yugoslav history',
    },
    {
        id: '17',
        text: 'The Yugoslav Partisan movement included one of the most active resistance printing operations in occupied Europe, producing newspapers and poetry in secret.',
        imageKeyword: 'yugoslav resistance newspaper',
        category: 'yugoslav history',
    },
    {
        id: '18',
        text: 'Belgrade was one of the first European capitals to have electric street lighting in the 19th century, reflecting early technological modernization.',
        imageKeyword: 'belgrade old city',
        category: 'yugoslav history',
    },
    {
        id: '19',
        text: 'Hummingbirds enter a nightly state called torpor, reducing their metabolic rate dramatically to conserve energy.',
        imageKeyword: 'hummingbird resting',
        category: 'animals',
    },
    {
        id: '20',
        text: 'Long-tailed tits often roost together in tight groups during winter, forming spherical clusters to conserve heat collectively.',
        imageKeyword: 'long-tailed tits winter',
        category: 'animals',
    },
    {
        id: '21',
        text: 'The physicist Lise Meitner provided the theoretical explanation for nuclear fission but was not included in the Nobel Prize awarded for the discovery.',
        imageKeyword: 'nuclear fission diagram',
        category: 'important women',
    },
    {
        id: '22',
        text: 'Emmy Noether\'s theorem demonstrated that every continuous symmetry in nature corresponds to a conservation law, fundamentally shaping modern theoretical physics.',
        imageKeyword: 'chalkboard equations',
        category: 'important women',
    },
    {
        id: '23',
        text: 'PinkPantheress gained recognition by producing and uploading short, self-produced tracks that blend early 2000s drum and bass influences with contemporary pop.',
        imageKeyword: 'music studio',
        category: 'music',
    },
    {
        id: '24',
        text: 'Ariana Grande has a four-octave vocal range and is known for her whistle register, which allows her to produce extremely high notes with clarity.',
        imageKeyword: 'concert stage lights',
        category: 'music',
    },
    {
        id: '25',
        text: 'Nikola Tesla once designed a small remote-controlled boat in 1898, one of the earliest demonstrations of radio-controlled technology.',
        imageKeyword: 'tesla radio boat',
        category: 'physics history',
    },
    {
        id: '26',
        text: 'Some flowering plants, such as orchids, form highly specialized mutualistic relationships with specific pollinators, sometimes depending on a single species.',
        imageKeyword: 'orchid flower close up',
        category: 'flowers',
    },
    {
        id: '27',
        text: 'Dogs can detect changes in human emotional states by interpreting subtle variations in facial expression and tone of voice.',
        imageKeyword: 'dog looking at owner',
        category: 'animals',
    },
    {
        id: '28',
        text: 'Cats use their whiskers to measure spatial dimensions and detect air currents, allowing precise movement even in low light.',
        imageKeyword: 'cat whiskers close up',
        category: 'animals',
    },
    {
        id: '29',
        text: 'During the 20th century, Yugoslavia promoted large-scale reforestation projects that restored significant forest coverage in previously degraded areas.',
        imageKeyword: 'balkan forest landscape',
        category: 'yugoslav history',
    },
    {
        id: '30',
        text: 'Hummingbirds perceive ultraviolet light, allowing them to see nectar guides on flowers that are invisible to humans.',
        imageKeyword: 'hummingbird ultraviolet vision',
        category: 'animals',
    },
    {
        id: '31',
        text: 'Hummingbirds have the highest mass-specific metabolic rate of any vertebrate, requiring them to consume nectar equivalent to more than half their body weight daily.',
        imageKeyword: 'hummingbird feeding',
        category: 'animals',
    },
    {
        id: '32',
        text: 'The feathers of hummingbirds contain microscopic plate-like structures that refract light, producing iridescent colors that change depending on viewing angle.',
        imageKeyword: 'iridescent hummingbird',
        category: 'animals',
    },
    {
        id: '33',
        text: 'Long-tailed tits maintain lifelong social bonds within extended family groups, often recognizing relatives by vocal contact calls.',
        imageKeyword: 'long-tailed tit group',
        category: 'animals',
    },
    {
        id: '34',
        text: 'In cold weather, long-tailed tits can reduce overnight heat loss by huddling in groups of up to 20 individuals.',
        imageKeyword: 'long-tailed tits huddling',
        category: 'animals',
    },
    {
        id: '35',
        text: 'Cats possess a reflective layer behind the retina called the tapetum lucidum, which enhances night vision by reflecting light back through photoreceptors.',
        imageKeyword: 'cat glowing eyes',
        category: 'animals',
    },
    {
        id: '36',
        text: 'Dogs are capable of detecting certain cancers through scent due to their highly developed olfactory epithelium, which contains hundreds of millions of scent receptors.',
        imageKeyword: 'dog sniffing',
        category: 'animals',
    },
    {
        id: '37',
        text: 'Lavender produces essential oils containing linalool, a compound shown to have mild anxiolytic effects in humans.',
        imageKeyword: 'lavender field',
        category: 'flowers',
    },
    {
        id: '38',
        text: 'Some alpine flowers exhibit cushion growth forms, creating compact hemispherical shapes that reduce wind exposure and retain heat.',
        imageKeyword: 'alpine cushion plant',
        category: 'flowers',
    },
    {
        id: '39',
        text: 'Certain species of orchids mimic the appearance and scent of female insects, inducing pollination through pseudocopulation.',
        imageKeyword: 'orchid close up',
        category: 'flowers',
    },
    {
        id: '40',
        text: 'In socialist Yugoslavia, the concept of “self-management” allowed workers to participate directly in the governance of enterprises through elected councils.',
        imageKeyword: 'yugoslav factory 1960s',
        category: 'yugoslav history',
    },
    {
        id: '41',
        text: 'The Yugoslav “Spomenik” monuments were designed as abstract concrete sculptures intended to symbolize collective resilience and antifascist resistance.',
        imageKeyword: 'spomenik monument',
        category: 'yugoslav history',
    },
    {
        id: '42',
        text: 'After World War II, Yugoslavia established one of the Non-Aligned Movement\'s founding leadership roles, positioning itself between Western and Eastern blocs.',
        imageKeyword: 'non aligned movement conference',
        category: 'yugoslav history',
    },
    {
        id: '43',
        text: 'Nikola Tesla developed the polyphase alternating current system, which enabled efficient long-distance electricity transmission.',
        imageKeyword: 'tesla alternating current diagram',
        category: 'physics history',
    },
    {
        id: '44',
        text: 'Tesla had an exceptional ability for visualizing mechanical devices in three dimensions and claimed he could run full simulations of machines entirely in his mind.',
        imageKeyword: 'electrical blueprint',
        category: 'physics history',
    },
    {
        id: '45',
        text: 'Marie Curie established mobile radiography units during World War I, enabling battlefield X-ray diagnostics and improving survival rates.',
        imageKeyword: 'vintage xray machine',
        category: 'important women',
    },
    {
        id: '46',
        text: 'Emmy Noether\'s work laid the mathematical foundation for gauge theory, which underpins the Standard Model of particle physics.',
        imageKeyword: 'math chalkboard',
        category: 'important women',
    },
    {
        id: '47',
        text: 'Chien-Shiung Wu conducted the experiment that experimentally confirmed parity violation in weak interactions, reshaping modern physics.',
        imageKeyword: 'physics lab equipment',
        category: 'important women',
    },
    {
        id: '48',
        text: 'Lise Meitner continued publishing scientific research even after fleeing Nazi Germany, maintaining collaborations through detailed written correspondence.',
        imageKeyword: 'nuclear research notes',
        category: 'important women',
    },
    {
        id: '49',
        text: 'Hummingbirds have proportionally the largest flight muscles relative to body size among birds, accounting for roughly 25–30% of their body mass.',
        imageKeyword: 'hummingbird in flight',
        category: 'animals',
    },
    {
        id: '50',
        text: 'Long-tailed tits line their nests with thousands of feathers, creating insulation that rivals some human-made thermal materials.',
        imageKeyword: 'long-tailed tit nest interior',
        category: 'animals',
    },
    {
        id: '51',
        text: 'Roses produce distinct volatile organic compounds that attract specific pollinators while deterring certain herbivores.',
        imageKeyword: 'rose close up',
        category: 'flowers',
    },
    {
        id: '52',
        text: 'Sunflowers optimize energy capture not only by tracking sunlight but also by orienting eastward at maturity, warming faster in the morning and attracting pollinators.',
        imageKeyword: 'sunflower sunrise',
        category: 'flowers',
    },
    {
        id: '53',
        text: 'In the 1960s, Yugoslavia permitted relatively open travel compared to other socialist states, allowing citizens to work temporarily abroad.',
        imageKeyword: 'yugoslav passport 1970s',
        category: 'yugoslav history',
    },
    {
        id: '54',
        text: 'Nikola Tesla described experiencing vivid sensory phenomena that he associated with intense creativity and imaginative visualization.',
        imageKeyword: 'wardenclyffe tower',
        category: 'physics history',
    },
    {
        id: '55',
        text: 'Marie Curie personally trained other women in laboratory techniques, contributing to the early inclusion of women in experimental physics.',
        imageKeyword: 'laboratory notes',
        category: 'important women',
    },
    {
        id: '56',
        text: 'Dogs exhibit “gaze-following” behavior, meaning they can follow human pointing gestures without prior training, a trait linked to domestication.',
        imageKeyword: 'dog following finger',
        category: 'animals',
    },
    {
        id: '57',
        text: 'Cats communicate contentment through rhythmic kneading behavior, a motor pattern retained from early nursing stages.',
        imageKeyword: 'cat kneading',
        category: 'animals',
    },
    {
        id: '58',
        text: 'PinkPantheress often samples early 2000s UK garage and drum and bass tracks, contributing to a revival of Y2K electronic aesthetics.',
        imageKeyword: 'studio microphone',
        category: 'music',
    },
    {
        id: '59',
        text: 'Ariana Grande began her career in musical theatre, and her early vocal training emphasized breath control and head voice development.',
        imageKeyword: 'stage lighting',
        category: 'music',
    },
    {
        id: '60',
        text: 'Certain flowering plants can detect the vibrations of pollinator wingbeats and temporarily increase nectar sugar concentration in response.',
        imageKeyword: 'flower with bee',
        category: 'flowers',
    },
    {
        id: '61',
        text: 'Shield bugs, called “stinky martins” in Croatian, release a pungent chemical from glands on their thorax as a defense mechanism against predators.',
        imageKeyword: 'shield bug',
        category: 'animals',
    },
    {
        id: '62',
        text: 'Some species of shield bugs exhibit maternal care by guarding their eggs until they hatch, which is rare among insects.',
        imageKeyword: 'shield bug guarding eggs',
        category: 'animals',
    },
    {
        id: '63',
        text: 'Honeybees communicate the location of flowers through a “waggle dance,” conveying both direction and distance with precise body movements.',
        imageKeyword: 'honeybee waggle dance',
        category: 'animals',
    },
    {
        id: '64',
        text: 'Bees can recognize human faces by processing visual patterns in a way similar to how humans do, which is remarkable for such small brains.',
        imageKeyword: 'bee on flower',
        category: 'animals',
    },
    {
        id: '65',
        text: 'Some flowers, like snapdragons, require “buzz pollination,” where bees vibrate their flight muscles to release pollen from the anthers.',
        imageKeyword: 'snapdragon flower',
        category: 'flowers',
    },
    {
        id: '66',
        text: 'The “Yugo” was a compact car produced in Yugoslavia during the 1980s, designed for affordable mobility for the average family.',
        imageKeyword: 'yugo car',
        category: 'yugoslav history',
    },
    {
        id: '67',
        text: 'Despite its reputation, the Yugo was innovative for its time, featuring simple mechanics that made it easy to repair even in rural areas.',
        imageKeyword: 'yugo car interior',
        category: 'yugoslav history',
    },
    {
        id: '68',
        text: 'Shield bugs have bright, often metallic coloration, which can serve as aposematic signaling, warning predators of their chemical defenses.',
        imageKeyword: 'colorful shield bug',
        category: 'animals',
    },
    {
        id: '69',
        text: 'Bees have five eyes — two large compound eyes and three smaller ocelli — which allow them to detect light polarization and navigate precisely.',
        imageKeyword: 'bee close up',
        category: 'animals',
    },
    {
        id: '70',
        text: 'Certain wildflowers coevolved with bees so that their shape, color, and scent maximize pollination efficiency while providing nectar rewards.',
        imageKeyword: 'wildflower bee',
        category: 'flowers',
    },
    {
        id: '71',
        text: 'Yugoslavia\'s automobile industry symbolized post-war modernization, and the Yugo became one of the few exports reaching Western Europe and the US.',
        imageKeyword: 'yugo on road',
        category: 'yugoslav history',
    },
    {
        id: '72',
        text: 'Shield bugs release chemicals not only for defense but sometimes as communication signals to attract mates or warn others of danger.',
        imageKeyword: 'shield bug chemical spray',
        category: 'animals',
    },
    {
        id: '73',
        text: 'Honeybees can remember the scents of dozens of flowers and associate them with high-energy rewards, effectively forming “floral memories.”',
        imageKeyword: 'honeybee smelling flower',
        category: 'animals',
    },
    {
        id: '74',
        text: 'The Yugo\'s design drew inspiration from Western compact cars but incorporated locally sourced materials and simplified assembly methods.',
        imageKeyword: 'yugo factory',
        category: 'yugoslav history',
    },
    {
        id: '75',
        text: 'Some shield bugs mimic ants or other insects as a form of protective camouflage, deceiving predators with harmless appearances.',
        imageKeyword: 'shield bug mimicry',
        category: 'animals',
    },
    {
        id: '76',
        text: 'Worker bees have a social immune system: they collectively remove sick larvae and maintain hive hygiene, preventing the spread of disease.',
        imageKeyword: 'bee hive',
        category: 'animals',
    },
    {
        id: '77',
        text: 'Bees can communicate through vibrations even inside the hive, allowing coordination of tasks like brood care, cleaning, and food distribution.',
        imageKeyword: 'bee hive interior',
        category: 'animals',
    },
    {
        id: '78',
        text: 'Certain flowers, like morning glories, have petal structures that appear differently under ultraviolet light, making hidden patterns visible to bees.',
        imageKeyword: 'morning glory flower',
        category: 'flowers',
    },
    {
        id: '79',
        text: 'The Yugo achieved a sort of cult status in pop culture for its quirky design and simplicity, inspiring both affection and humor among car enthusiasts.',
        imageKeyword: 'yugo retro',
        category: 'yugoslav history',
    },
    {
        id: '80',
        text: 'Shield bugs are part of a large family of insects called Pentatomidae, and some species are actually beneficial for agriculture by preying on pest insects.',
        imageKeyword: 'shield bug on leaf',
        category: 'animals',
    },
    {
        id: '81',
        text: 'The term “bug” in programming comes from a real moth that was found stuck in the Harvard Mark II computer in 1947, causing a malfunction.',
        imageKeyword: 'moth in computer',
        category: 'programming',
    },
    {
        id: '82',
        text: 'Grace Hopper, a pioneering computer scientist, popularized the term “debugging” and developed one of the first compilers for a computer programming language.',
        imageKeyword: 'early computer',
        category: 'important women',
    },
    {
        id: '83',
        text: 'Ada Lovelace, often considered the first computer programmer, wrote algorithms for Charles Babbage\'s Analytical Engine in the 1840s, long before actual computers existed.',
        imageKeyword: 'analytical engine',
        category: 'important women',
    },
    {
        id: '84',
        text: 'The programming language Python was named after “Monty Python\'s Flying Circus,” not the snake, reflecting its creator\'s sense of humor.',
        imageKeyword: 'python logo',
        category: 'programming',
    },
    {
        id: '85',
        text: 'Katherine Johnson, the mathematician behind NASA\'s orbital calculations, manually computed trajectories that helped send astronauts safely to space.',
        imageKeyword: 'nasa calculations',
        category: 'important women',
    },
    {
        id: '86',
        text: 'Sophie Brahe, a 16th-century Danish astronomer and horticulturist, collaborated with her brother Tycho Brahe to record precise astronomical observations.',
        imageKeyword: 'old observatory',
        category: 'important women',
    },
    {
        id: '87',
        text: 'Hedy Lamarr, a famous actress, co-invented a frequency-hopping system during WWII, which later became a foundation for Wi-Fi and Bluetooth technology.',
        imageKeyword: 'radio frequency diagram',
        category: 'important women',
    },
    {
        id: '88',
        text: 'Programming languages like JavaScript were originally designed in just 10 days by Brendan Eich in 1995, an astonishingly short development time.',
        imageKeyword: 'javascript logo',
        category: 'programming',
    },
    {
        id: '89',
        text: 'Mary Anning, a fossil collector in early 19th-century England, discovered several significant prehistoric specimens, greatly advancing paleontology despite gender bias.',
        imageKeyword: 'fossil excavation',
        category: 'important women',
    },
    {
        id: '90',
        text: 'Ida B. Wells used investigative journalism and meticulous data collection to expose lynching in the US, demonstrating that activism and statistics can intersect.',
        imageKeyword: 'vintage newspaper',
        category: 'important women',
    },
    {
        id: '91',
        text: 'Joan Clarke was a cryptanalyst at Bletchley Park who helped break the Enigma code during WWII, her contributions historically overshadowed despite vital importance.',
        imageKeyword: 'enigma machine',
        category: 'important women',
    },
    {
        id: '92',
        text: 'Women programmers were dominant in early computing; during WWII, most of the “human computers” calculating trajectories were women.',
        imageKeyword: 'vintage computing room',
        category: 'important women',
    },
    {
        id: '93',
        text: 'Frances E. Allen was the first female IBM Fellow and a pioneer in optimizing compilers, a crucial advancement in modern programming efficiency.',
        imageKeyword: 'computer code',
        category: 'important women',
    },
    {
        id: '94',
        text: 'The first programming “loop” concept was described by Ada Lovelace as a way for Babbage\'s Analytical Engine to repeat a sequence of operations.',
        imageKeyword: 'ada lovelace diagram',
        category: 'programming',
    },
    {
        id: '95',
        text: 'Radia Perlman, known as the “Mother of the Internet,” invented the spanning-tree protocol that made Ethernet networks scalable and reliable.',
        imageKeyword: 'network cables',
        category: 'important women',
    },
    {
        id: '96',
        text: 'The first computer mouse prototype was made of wood and created by Doug Engelbart in 1964, long before mice looked like the ones we use today.',
        imageKeyword: 'wooden computer mouse',
        category: 'programming',
    },
    {
        id: '97',
        text: 'Claudette Colvin, at age 15, refused to give up her bus seat in Montgomery before Rosa Parks, showing courageous activism that is lesser-known but pivotal.',
        imageKeyword: 'civil rights bus',
        category: 'important women',
    },
    {
        id: '98',
        text: 'Suffragist Emmeline Pankhurst once organized a “human chain” around the British Parliament to demonstrate women\'s determination for the vote in 1907.',
        imageKeyword: 'suffragette march',
        category: 'important women',
    },
    {
        id: '99',
        text: 'Programming languages often get quirky Easter eggs; for example, in Python, typing “import this” prints the “Zen of Python,” a philosophy of coding style.',
        imageKeyword: 'python code zen',
        category: 'programming',
    },
    {
        id: '100',
        text: 'Hypatia of Alexandria was a mathematician and philosopher in the 4th century who taught thousands of students, one of the earliest documented women in STEM.',
        imageKeyword: 'ancient greek building',
        category: 'important women',
    },
];
